In [1]:
import pandas as pd 
df = pd.read_csv('credit_card_fraud_10k.csv')
x = df.isnull().values.any()
print(x)

True

In [2]:
y = df.isnull().sum()
print(y)

transaction_id           0
amount                  63
transaction_hour         0
merchant_category        0
foreign_transaction      0
location_mismatch        0
device_trust_score     125
velocity_last_24h        0
cardholder_age           0
is_fraud                 0
dtype: int64

In [3]:
x = df.isna()
print(x)

      transaction_id  amount  transaction_hour  merchant_category  \
0              False   False             False              False
1              False   False             False              False
2              False   False             False              False
3              False   False             False              False
4              False   False             False              False
...              ...     ...               ...                ...
9995           False   False             False              False
9996           False   False             False              False
9997           False    True             False              False
9998           False   False             False              False
9999           False   False             False              False

      foreign_transaction  location_mismatch  device_trust_score  \
0                   False              False               False
1                   False              False               False
2                   False              False               False
3                   False              False               False
4                   False              False               False
...                   ...                ...                 ...
9995                False              False               False
9996                False              False               False
9997                False              False               False
9998                False              False                True
9999                False              False               False

      velocity_last_24h  cardholder_age  is_fraud
0                 False           False     False
1                 False           False     False
2                 False           False     False
3                 False           False     False
4                 False           False     False
...                 ...             ...       ...
9995              False           False     False
9996              False           False     False
9997              False           False     False
9998              False           False     False
9999              False           False     False

[10000 rows x 10 columns]

In [4]:
y1 = df.notnull()
print(y1)

      transaction_id  amount  transaction_hour  merchant_category  \
0               True    True              True               True
1               True    True              True               True
2               True    True              True               True
3               True    True              True               True
4               True    True              True               True
...              ...     ...               ...                ...
9995            True    True              True               True
9996            True    True              True               True
9997            True   False              True               True
9998            True    True              True               True
9999            True    True              True               True

      foreign_transaction  location_mismatch  device_trust_score  \
0                    True               True                True
1                    True               True                True
2                    True               True                True
3                    True               True                True
4                    True               True                True
...                   ...                ...                 ...
9995                 True               True                True
9996                 True               True                True
9997                 True               True                True
9998                 True               True               False
9999                 True               True                True

      velocity_last_24h  cardholder_age  is_fraud
0                  True            True      True
1                  True            True      True
2                  True            True      True
3                  True            True      True
4                  True            True      True
...                 ...             ...       ...
9995               True            True      True
9996               True            True      True
9997               True            True      True
9998               True            True      True
9999               True            True      True

[10000 rows x 10 columns]

In [5]:
a = pd.notnull(df["amount"])
print(a)

0        True
1        True
2        True
3        True
4        True
        ...
9995     True
9996     True
9997    False
9998     True
9999     True
Name: amount, Length: 10000, dtype: bool

In [6]:
df.fillna(0)

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66.0,3,40,0
1,2,541.82,3,Travel,1,0,87.0,1,64,0
2,3,237.01,17,Grocery,0,0,49.0,1,61,0
3,4,164.33,4,Grocery,0,1,72.0,3,34,0
4,5,30.53,15,Food,0,0,79.0,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99.0,4,37,0
9996,9997,410.04,5,Clothing,0,0,70.0,3,25,0
9997,9998,0.00,21,Electronics,0,0,44.0,2,45,0
9998,9999,91.20,2,Electronics,0,0,0.0,0,37,0
9999,10000,44.06,2,Clothing,0,0,38.0,0,66,0

In [11]:
df.ffill()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66.0,3,40,0
1,2,541.82,3,Travel,1,0,87.0,1,64,0
2,3,237.01,17,Grocery,0,0,49.0,1,61,0
3,4,164.33,4,Grocery,0,1,72.0,3,34,0
4,5,30.53,15,Food,0,0,79.0,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99.0,4,37,0
9996,9997,410.04,5,Clothing,0,0,70.0,3,25,0
9997,9998,410.04,21,Electronics,0,0,44.0,2,45,0
9998,9999,91.20,2,Electronics,0,0,44.0,0,37,0
9999,10000,44.06,2,Clothing,0,0,38.0,0,66,0

In [31]:
df.bfill()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66.0,3,40,0
1,2,541.82,3,Travel,1,0,87.0,1,64,0
2,3,237.01,17,Grocery,0,0,49.0,1,61,0
3,4,164.33,4,Grocery,0,1,72.0,3,34,0
4,5,30.53,15,Food,0,0,79.0,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99.0,4,37,0
9996,9997,410.04,5,Clothing,0,0,70.0,3,25,0
9997,9998,250.62,21,Electronics,0,0,44.0,2,45,0
9998,9999,91.20,2,Electronics,0,0,41.0,0,37,0
9999,10000,44.06,2,Clothing,0,0,38.0,0,66,0

In [33]:
df.dropna()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66.0,3,40,0
1,2,541.82,3,Travel,1,0,87.0,1,64,0
2,3,237.01,17,Grocery,0,0,49.0,1,61,0
3,4,164.33,4,Grocery,0,1,72.0,3,34,0
4,5,30.53,15,Food,0,0,79.0,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99.0,4,37,0
9996,9997,410.04,5,Clothing,0,0,70.0,3,25,0
9997,9998,250.62,21,Electronics,0,0,44.0,2,45,0
9998,9999,91.20,2,Electronics,0,0,41.0,0,37,0
9999,10000,44.06,2,Clothing,0,0,38.0,0,66,0

In [34]:
df.dropna(how = 'all')

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66.0,3,40,0
1,2,541.82,3,Travel,1,0,87.0,1,64,0
2,3,237.01,17,Grocery,0,0,49.0,1,61,0
3,4,164.33,4,Grocery,0,1,72.0,3,34,0
4,5,30.53,15,Food,0,0,79.0,0,44,0
...,...,...,...,...,...,...,...,...,...,...
9995,9996,350.91,22,Food,0,0,99.0,4,37,0
9996,9997,410.04,5,Clothing,0,0,70.0,3,25,0
9997,9998,250.62,21,Electronics,0,0,44.0,2,45,0
9998,9999,91.20,2,Electronics,0,0,41.0,0,37,0
9999,10000,44.06,2,Clothing,0,0,38.0,0,66,0